spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: root
    password: ITadmin999
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security=DEBUG: